GET https://www.cheapshark.com/api/1.0/deals?pageSize=10&lowerPrice=2&steamRating=50&metacritic=50
###
GET https://www.cheapshark.com/api/1.0/deals?pageSize=10&sortBy=Savings&steamRating=90&metacritic=90&lowerPrice=5
###
GET https://www.cheapshark.com/api/1.0/deals?pageSize=10&sortBy=Reviews
###
GET https://www.cheapshark.com/api/1.0/deals?pageSize=10&sortBy=recent
###
GET https://www.cheapshark.com/api/1.0/games?title=Dirt+Rally
###
GET https://www.cheapshark.com/api/1.0/games?id=143429
###
GET https://www.cheapshark.com/api/1.0/deals?id=g1DVDtUwRhv8unj0mei1OS9ajgmc9pn3LxBTn%2BbsN7M%3D
###
GET https://www.cheapshark.com/api/1.0/deals?storeID=1&pageSize=24&sortBy=Deal+Rating&desc=1